Add better error checking of Jekyll builds for Travis

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 set -e # halt script on error
 
-bundle exec jekyll build
+JEKYLLBUILDOUTPUT="$(bundle exec jekyll build)"
+echo "${JEKYLLBUILDOUTPUT}"
+if echo "${JEKYLLBUILDOUTPUT}" | grep -i -q "ERROR"; then
+    printf '%s\n' 'An Error was found in the Jekyll build' >&2
+    exit 1
+fi
 bundle exec 'htmlproof ./_site --href_ignore "#"'
